# Golang
[[language]]
name = "go"
roots = ["go.work", "go.mod"]
auto-format = true
formatter = ["gofmt"]
comment-token = "//"
language-servers = [ "gopls" ]


[language-server.golangci-lint-lsp.config]
command = ["golangci-lint", "run", "--out-format", "json", "--issues-exit-code=1"]


[language-server.gopls]
command = "gopls"

[language-server.gopls.config]
completeUnimported = true
usePlaceholders = true

[language-server.gopls.config.hints]
assignVariableType = true
compositeLiteralFields = true
compositeLiteralTypes = true
constantValues = true
functionTypeParameters = true
parameterNames = true
rangeVariableTypes = true

# Python
# Python language configuration
[[language]]
name = "python"
scope = "source.python"
file-types = [
    "py", "pyi", "py3", "pyw", "ptl", "rpy", "cpy", "ipy", "pyt",
    { glob = ".python_history" },
    { glob = ".pythonstartup" },
    { glob = ".pythonrc" },
    { glob = "SConstruct" },
    { glob = "SConscript" }
]
shebangs = ["python"]
roots = [
    "pyproject.toml",
    "setup.py",
    "poetry.lock",
    "pyrightconfig.json",
    "requirements.txt",
    ".venv/"
]
comment-token = "#"
indent = { tab-width = 4, unit = "    " }

# Enable formatting
auto-format = true
formatter = { command = "black", args = ["--quiet", "-"] }

# Use both pyright and ruff as language servers
language-servers = [
    { name = "pyright", except-features = ["diagnostics"] },
    "ruff"
]

# pyright language server config
[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config.python.analysis]
venvPath = "."
venv = ".venv"
lint = true
inlayHint.enable = true
autoSearchPaths = true
diagnosticMode = "workspace"
useLibraryCodeForType = true
logLevel = "Error"
typeCheckingMode = "off"
autoImportCompletion = true
reportOptionalSubscript = false
reportOptionalMemberAccess = false

# ruff as a language server
[language-server.ruff]
command = "ruff"
args = ["server", "-q", "--preview"]


# Rust
[[language]]
name = "rust"
file-types = ["rs"]
roots = ["Cargo.toml"]
auto-format = true
language-servers = ["rust-analyzer"]
#formatter = { command = "rustfmt"}
#formatter = { command = "cargo", args = ["fmt"] }

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.rust-analyzer.config.cargo]
features = "all"


# Markdown
[language-server.marksman]
command = "marksman"

[language-server.markdown-oxide]
command = "markdown-oxide"

[[language]]
name = "markdown"
language-servers = ["marksman", "markdown-oxide"]
