# Golang
[[language]]
name = "go"
roots = ["go.work", "go.mod"]
auto-format = true
formatter = ["gofmt"]
comment-token = "//"
language-servers = [ "gopls" ]


[language-server.golangci-lint-lsp.config]
command = ["golangci-lint", "run", "--out-format", "json", "--issues-exit-code=1"]


# Python
[[language]]
name = "python"
scope = "source.python"
auto-format = true
indent = { tab-width = 4, unit = " " }
formatter = { command = "black", args = ["-", "-q"] }
roots = ["pyproject.toml", "pyrightconfig.json", "Poetry.lock"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
[language-server.pyright.config]
lint = true
inlayHint.enable = true

[language-server.ruff-lsp]
command = "ruff-lsp"
args = ["--stdio"]

# Enable ruff via pylsp plugin (if using pylsp)
[language-server.pylsp.config.pylsp.plugins.ruff]
lineLength = 88
preview = true
select = ["E4", "E7", "E9", "F"]
ignore = ["D210"]


# Rust
[[language]]
name = "rust"
file-types = ["rs"]
roots = ["Cargo.toml"]
auto-format = true
language-servers = ["rust-analyzer"]
#formatter = { command = "rustfmt"}
#formatter = { command = "cargo", args = ["fmt"] }

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.rust-analyzer.config.cargo]
features = "all"
