# Go language configuration
[[language]]
name = "go"
roots = ["go.work", "go.mod"]
auto-format = true
formatter = ["goimports"]
comment-token = "//"

# addinf lint-lsp github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.10.1
language-servers = ["gopls", "golangci-lint-lsp"]

# Primary Go language server
[language-server.gopls]
command = "gopls"

[language-server.gopls.config]
# You can customize gopls settings here if needed
completeUnimported = true
usePlaceholders = true

# Linter server powered by golangci-lint
[language-server.golangci-lint-lsp]
command = "golangci-lint-langserver"

[language-server.golangci-lint-lsp.config]
# Make sure this matches how golangci-lint outputs JSON
command = ["golangci-lint", "run", "--output.json.path", "stdout", "--show-stats=false", "--issues-exit-code=1"]

# Python
# Python language configuration
[[language]]
name = "python"
scope = "source.python"
file-types = [
    "py", "pyi", "py3", "pyw", "ptl", "rpy", "cpy", "ipy", "pyt",
    { glob = ".python_history" },
    { glob = ".pythonstartup" },
    { glob = ".pythonrc" },
    { glob = "SConstruct" },
    { glob = "SConscript" }
]
shebangs = ["python"]
roots = [
    "pyproject.toml",
    "setup.py",
    "poetry.lock",
    "pyrightconfig.json",
    "requirements.txt",
    ".venv/"
]
comment-token = "#"
indent = { tab-width = 4, unit = "    " }

# Enable formatting
auto-format = true
formatter = { command = "black", args = ["--quiet", "-"] }

# Use both pyright and ruff as language servers
language-servers = [
    { name = "pyright", except-features = ["diagnostics"] },
    "ruff"
]

# pyright language server config
[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config.python.analysis]
venvPath = "."
venv = ".venv"
lint = true
inlayHint.enable = true
autoSearchPaths = true
diagnosticMode = "workspace"
useLibraryCodeForType = true
logLevel = "Error"
typeCheckingMode = "off"
autoImportCompletion = true
reportOptionalSubscript = false
reportOptionalMemberAccess = false

# ruff as a language server
[language-server.ruff]
command = "ruff"
args = ["server", "-q", "--preview"]


# Rust
[[language]]
name = "rust"
file-types = ["rs"]
roots = ["Cargo.toml"]
auto-format = true
language-servers = ["rust-analyzer"]
#formatter = { command = "rustfmt"}
#formatter = { command = "cargo", args = ["fmt"] }

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.rust-analyzer.config.cargo]
features = "all"


# Markdown
[language-server.marksman]
command = "marksman"

[language-server.markdown-oxide]
command = "markdown-oxide"

[[language]]
name = "markdown"
language-servers = ["marksman", "markdown-oxide"]
